hide_agent_reasoning = true
model_reasoning_effort = 'high'
network_access = true

[features]
web_search_request = true

[mcp_servers]
[mcp_servers.context7]
args = ['@upstash/context7-mcp@latest']
command = 'pnpx'

[mcp_servers.playwright]
args = ['@playwright/mcp@latest']
command = 'pnpx'

[mcp_servers.readability]
args = ['@mizchi/readability@latest', '--mcp']
command = 'pnpx'
