model_reasoning_effort = "high"
hide_agent_reasoning = true
network_access = true

[tools]
web_search = true

[mcp_servers.context7]
command = "pnpx"
args = ["@upstash/context7-mcp@latest"]

[mcp_servers.readability]
command = "pnpx"
args = ["@mizchi/readability@latest", "--mcp"]

[mcp_servers.playwright]
command = "pnpx"
args = ["@playwright/mcp@latest"]
