[settings]
idiomatic_version_file_enable_tools = ["node"]

[tools]
bun = "1.3.2"
deno = "2.5.6"
direnv = "2.37.1"
gitleaks = "8.30.0"
go = "1.25.4"
node = "24.11.0"
pnpm = "10.20.0"
rust = "1.91.0"
yarn = "4.10.3"
